const GET_BANNER_LIST_HOME = "GET_BANNER_LIST_HOME";
const GET_GOODS_LIST_HOME = "GET_GOODS_LIST_HOME";
const GET_MENU_LIST_HOME = "GET_MENU_LIST_HOME";
const GET_LOGIN_INFO = "GET_LOGIN_INFO";
const GET_LOGINING_USER = "GET_LOGINING_USER";
const GET_MORE_SORT = "GET_MORE_SORT";
const GET_GOODS_LIST_DRINK = "GET_GOODS_LIST_DRINK";
const GET_GOODS_DETAIL = "GET_GOODS_DETAIL";
const GET_GOODS_SHOPCAR = "GET_GOODS_SHOPCAR";


export {
    GET_BANNER_LIST_HOME,
    GET_GOODS_LIST_HOME,
    GET_MENU_LIST_HOME,
    GET_LOGIN_INFO,
    GET_LOGINING_USER,
    GET_MORE_SORT,
    GET_GOODS_LIST_DRINK, 
    GET_GOODS_DETAIL,
    GET_GOODS_SHOPCAR
    

}